kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: rancher/dapper:v0.4.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - CROSS=1 dapper ci
  - name: publish-rke-tools-amd64
    image: plugins/docker
    settings:
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      dockerfile: Dockerfile
      repo: jianghang8421/dapper
      tag: "${DRONE_TAG}-amd64"
    when:
      event:
        - tag
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: rancher/dapper:v0.4.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - dapper ci
  - name: publish-rke-tools-arm64
    image: plugins/docker:linux-arm64 
    settings:
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      dockerfile: Dockerfile
      repo: jianghang8421/dapper
      tag: "${DRONE_TAG}-arm64"
    when:
      event:
        - tag
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
---
kind: pipeline
name: manifest

steps:
  - name: push-manifest
    image: plugins/manifest:1.0.2
    settings:
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      target: "jianghang8421/dapper:${DRONE_TAG}"
      template: "jianghang8421/dapper:${DRONE_TAG}-ARCH"
      platforms:
        - linux/amd64
        - linux/arm64
    when:
      event:
        - tag
depends_on:
- amd64
- arm64